# Generated by Django 5.2 on 2025-08-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTable',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('examName', models.CharField(max_length=255)),
                ('examduration', models.IntegerField(help_text='Duration in minutes')),
                ('cource_id', models.CharField(max_length=100)),
                ('total_no_questions', models.IntegerField()),
                ('questionarray', models.JSONField(help_text='List of Question IDs')),
                ('passmarks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTable',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField()),
                ('OptionA', models.CharField(max_length=255)),
                ('OptionB', models.CharField(max_length=255)),
                ('OptionC', models.CharField(max_length=255)),
                ('OptionD', models.CharField(max_length=255)),
                ('RightOption', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('Marks', models.IntegerField()),
                ('Remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
