# Generated by Django 5.2 on 2025-08-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtable',
            name='exam_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
