# Generated by Django 4.2.23 on 2025-08-31 18:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examtable_exam_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontable',
            name='Question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
