# Generated by Django 4.2.23 on 2025-08-31 18:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_questiontable_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontable',
            name='OptionA',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questiontable',
            name='OptionB',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questiontable',
            name='OptionC',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questiontable',
            name='OptionD',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
